services:
  server:
    build: ./server
    restart: always
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - SA_PASSWORD=${SA_PASSWORD:-yourStrong#Passw0rd}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET:-yourJWTs3cr3t}

  client:
    build: ./client
    restart: always
    ports:
      - "${CLIENT_PORT:-4200}:80"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-yourStrong#Passw0rd}"
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data: